[package]
name = "public-ip-getter-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.20"
tokio = { version = "1.32.0", features = ["full"] }
structopt = "0.3.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.107"

